name: 'Terraform GCP Pub/Sub'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Configure GCP Credentials'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{secrets.GOOGLE_CREDENTIALS}}'

      - name: 'Initialize Terraform'
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      - name: 'Plan Terraform'
        run: terraform plan -var="project-id=${{secrets.GCP_PROJECT_ID}}" -var="region=${{secrets.GCP_REGION}}"
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

      - name: 'Apply Terraform'
        if: github.ref == 'refs/head/main'
        run: terraform apply -auto-approve -var="project-id=${{secrets.GCP_PROJECT_ID}}" -var="region=${{secrets.GCP_REGION}}"
        env:
          GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}


