name: 'Terraform GCP Pub/Sub'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          create_credentials_file: true
          export_environment_variables: true

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Initialize Terraform'
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: 'Plan Terraform'
        run: terraform plan -var="project_id=${{secrets.GCP_PROJECT_ID}}" -var="region=${{secrets.GCP_REGION}}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: 'Apply Terraform'
        run: terraform apply -auto-approve -var="project-id=${{secrets.GCP_PROJECT_ID}}" -var="region=${{secrets.GCP_REGION}}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}


